spring:
#  application:
#    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: recommendation-ai-service
              uri: lb://recommendation-ai-service
              predicates:
                - Path=/api/recommendations/**
            - id: activity-service
              uri: lb://activity-service
              predicates:
                - Path=/api/activities/**

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




