### CREATE A NEW USER ENTITY
POST http://localhost:8081/api/users/register
#Authorization: Bearer <paste your fresh token here>
Content-Type: application/json

{
  "email": "prititest@gmail.com",
  "password": "Priti@123",
  "firstName": "Priti",
  "lastName": "Test"
}

### Utilize Postman for generating a new token from Keycloak