### GET REQUEST TO VALIDATE USER ID EXISTS OR NOT.

GET http://localhost:8081/api/users/31cc2f8c-2fba-4580-90df-5c757e840ff4/validate
#Authorization: Bearer <paste your fresh token here>
Content-Type: application/jsons

### Utilize Postman for generating a new token from Keycloak