### Get user activities by userId header
#GET http://localhost:8082/api/activities
#API GATEWAY URL:
GET http://localhost:8080/api/activities
X-User-ID: 894dcfe7-9c28-43e7-881e-bc818fbc77a7
Accept: application/json
